### ISSUE TITLE
Chest Stealer

### ISSUE THREAD

**Issue by steviebeenz** [MSWS/NOPE#76]
**Is your feature request related to a problem/bug?**
Yes, people can use Chest Stealer

**Describe the solution you'd like**

I would like to see a chest stealer

**Have you tried implementing this solution alternatively?**
No

**Additional context**
Add any other context or screenshots about the recommendation please put here.

No

**Comment by MSWS** [comment]
Chest stealer is a simple hack but extremely difficult to detect, multiple movements of the inventory are possible due to single, double, triple, Q, shift, left, etc. etc. I have tried to implement a chest stealer previously and it still caused false flags. I may look into it in the future however for now it will remain unadded.
